@echo off
rem
rem Copy files for all cpp and header files from ../src hierarchy
rem 

if "%1" == "atmega2560" (
    echo Configuring for %1
) else if "%1" == "esp32" (
    echo Configuring for %1
) else (
    echo.
    echo Select a platform: atmega2560 or esp32
    echo.
    goto end
)

set LOCALCONFIGTEMPLATE=TXosLocalConfig.template
set LOCALCONFIG=TXosLocalConfig.h

set SOURCE=..\src ..\src\controls ..\src\modules ..\src\output ..\src\TextUI %1

if exist keep_file (
    del keep_file
)

if exist %LOCALCONFIG% (
    ren %LOCALCONFIG% keep_file
)

for /D %%S in ( %SOURCE% ) do (
    echo.
    echo Copy from %%S

    for %%F in ( %%S\*.cpp ) do (
        set TARGET=.
        echo %%F to %TARGET%
        copy %%F %TARGET%
    )

    for %%F in ( %%S\*.h ) do (
        set TARGET=.
        echo %%F to %TARGET%
        copy %%F %TARGET%
    )
)

echo.
echo Deleting  Arduino.h TXosTest.cpp TXosUnitTest.cpp TXosUnittestConfig.h TXos.ino
del %LOCALCONFIG% Arduino.h TXosTest.cpp TXosUnitTest.cpp TXosUnittestConfig.h TXos.ino

echo.
echo Renaming TXos.cpp to TXos.ino
ren TXos.cpp TXos.ino

if exist keep_file (
    ren keep_file %LOCALCONFIG%
)

if exist %LOCALCONFIG% ( 
    echo.
    echo Local config %LOCALCONFIG% exists. Not overwritten.
    echo.
    echo Please check your configuration.
    echo.
) else (
    copy %LOCALCONFIGTEMPLATE% %LOCALCONFIG%
    echo.
    echo Local config does not exist.
    echo A new %LOCALCONFIG% has been generated by copying the template file.
    echo.
    echo Please modify your local config to your needs.
    echo.
)

:end

